Adding basic visualization for organization list using P5.js
summerofcode/gsoc-orgs pull request #16
Opened 2018-03-08 17:45 UTC by BlinfoldKing

2018-03-11 01:00 UTC, jayvdb requested changes
Please rebase, and also use CDN URLs instead of adding vendor javascript code to this repo

2018-03-11 01:00 UTC, jayvdb commented on jsonloader.js
> +    xobj.open('GET', './_data/orgs.json', true);
this file wasnt being published, but I've fixed that: https://github.com/summerofcode/gsoc-orgs/commit/34243808e3d2afabd397c435756767bafdaf2d72

2018-03-11 01:04 UTC, jayvdb commented
@gitmate-bot rebase

2018-03-11 01:04 UTC, jayvdb commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

2018-03-11 01:04 UTC, jayvdb commented
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

2018-03-11 01:06 UTC, jayvdb commented
yay, preview is working https://deploy-preview-16--soc-orgs.netlify.com/list.html

2018-03-11 01:09 UTC, jayvdb commented on visualizer.js
> +        document.getElementById('web').setAttribute('href', node[index].website_url
change this to point to the generated page, e.g. https://soc-orgs.netlify.com/orgs/aimacode

2018-03-11 02:50 UTC, wisn requested changes
We need to use a JavaScript standard style such as [Standard](https://standardjs.com/).

2018-03-11 02:50 UTC, wisn commented on jsonloader.js
> +        if (xobj.readyState == 4 && xobj.status == "200") {
Use `===` instead of `==`. `"200"` should be an integer.

2018-03-11 02:50 UTC, wisn commented on list.html
> +		width: 25%;
Inconsistent indentation.

2018-03-11 02:50 UTC, wisn commented on jsonloader.js
> +loadData = (cb) => {
`(cb)` doesn't need brackets. `loadData = cb => {` is fine.

2018-03-11 02:50 UTC, wisn commented on visualizer.js
> +    if(category.find(value => value.category_name == element.category) == null)
Give a space after `if` keyword and use `===` instead of `==`.

2018-03-11 02:50 UTC, wisn commented on visualizer.js
> +  return [x - screenWidth()/2, y - screenHeight()/2]
`const getcoord = (x, y) => [x - screenWidth()/2, y - screenHeight()/2]` is equivalence.

2018-03-12 04:43 UTC, jayvdb requested changes

2018-03-12 04:43 UTC, jayvdb commented on visualizer.js
> +          document.getElementById('web').setAttribute('href', node[index].website_url)
This still needs fixing: https://github.com/summerofcode/gsoc-orgs/pull/16#discussion_r173640150

2018-03-12 04:47 UTC, jayvdb commented
On the view of a single category, with lots of orgs, what is determining the layout.  The placement of the org nodes doesnt have an obvious purpose.  If there is a good reason for the layout, maybe add a note explaining it to the user.

2018-03-12 04:53 UTC, BlinfoldKing commented
the orgs is currently spawn at random position, i'm currently still searching for a way to represent the data.

2018-03-12 13:41 UTC, jayvdb requested changes
Please use CDN URLs instead of adding vendor javascript code to this repo

2018-03-12 14:38 UTC, jayvdb commented
Also need to replace `jquery` & `p5` with CDN versions.

2018-03-12 14:46 UTC, BlinfoldKing commented
i've already replace it with the cdn version

2018-03-12 14:54 UTC, jayvdb commented
Nice, I must have been looking at an old version.

Can you lint all of your JS code with [`standard`](https://github.com/standard/standard).  c.f. https://github.com/summerofcode/gsoc-orgs/issues/19

Then squash your commits into a single commit if you want to.  If you dont, I have to squash it, which means that I become the git `Committer` on your patch.

2018-03-27 14:42 UTC, merged